# Estimated first install + boot time - 25~ minutes
# Estimated non first time startup - 1.5~ minutes
services:
  # Windows VM that will run processorKyber
  win-kyber:
    image: dockurr/windows
    container_name: win-kyber
    environment:
      VERSION: "2025"
      EDITION: "core"
      RAM_SIZE: "6G"
      CPU_CORES: "2"
      USERNAME: "Docker"      # default user (can change)
      PASSWORD: "admin"       # default pass (can change)
      # Optional: give Windows its own L2 IP later (see macvlan note)
      # DHCP: "Y"
      ARGUMENTS: "-cpu host,arch_capabilities=off" # MUST for Windows 11 to work : https://github.com/dockur/windows/issues/1301#issuecomment-3062008123
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"           # web viewer (install phase / emergency)
      - "5003:5000"           # Flask inside Windows -> exposed as 5001 on host/network
    volumes:
      - ./oem/kyber:/oem      # auto-run installer at first boot
      - ./:/data              # shows up inside Windows as \\host.lan\Data
      - ./windows-kyber:/storage
    restart: unless-stopped
    stop_grace_period: 2m
    networks:
      - pqbench-win

  # Windows VM that will run processorMLKEM
  win-mlkem:
    image: dockurr/windows
    container_name: win-mlkem
    environment:
      VERSION: "2025"
      RAM_SIZE: "6G"
      EDITION: "core"
      CPU_CORES: "2"
      ARGUMENTS: "-cpu host,arch_capabilities=off" # MUST for Windows 11 to boot consistently: https://github.com/dockur/windows/issues/1301#issuecomment-3062008123
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8007:8006"
      - "5004:5000"
    volumes:
      - ./oem/mlkem:/oem
      - ./:/data
      - ./windows-mlkem:/storage
    restart: unless-stopped
    stop_grace_period: 2m
    networks:
      - pqbench-win


networks:
  pqbench-win:
    driver: bridge
